title: Find The Duck
description: >-
  Bay is a minimal Jekyll Theme.
baseurl: "/find_the_duck"
url: "https://frdedynamics.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

plugins:
  - jekyll-feed

header:
  pages:
    - name: Home
      slug: /
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: gizem.ates@hvl.no
  follow:
    - type: instagram
      name: Instagram
      link: https://www.instagram.com/hvlrobotics/
    - type: youtube
      name: Youtube
      link: https://www.youtube.com/channel/UCL522yQ45L9ilPHQG5TQXBg
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/company/81467872/admin/dashboard/
    - type: github
      name: GitHub
      link: https://github.com/frdedynamics
    - type: rss
      name: RSS
      link: /feed.xml

[supabase_url]: "$SUPABASE_URL"
[supabase_key]: "$SUPABASE_KEY"

# Build settings
markdown: kramdown
sass:
    style: :compressed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1