name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your default branch
  workflow_dispatch:  # Add this line to allow manual triggers

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Change to your required Ruby version

    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle install

    - name: Build Jekyll site
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "supabase_url: $SUPABASE_URL" >> _config.yml
        echo "supabase_anon_key: $SUPABASE_KEY" >> _config.yml
        JEKYLL_ENV=production bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
