name: Deploy Jekyll site to GitHub Pages

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:  # Add this line to allow manual triggers

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Change to your required Ruby version

    - name: Install dependencies
      run: |
        gem install bundler -v 2.4.22
        bundle install

    - name: Add environment variables to Jekyll config
      run: |
        echo "supabase_url: $SUPABASE_URL" >> _config_prod.yml
        echo "supabase_key: $SUPABASE_KEY" >> _config_prod.yml
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }} 

    - name: Build site
      env:
        JEKYLL_ENV: production
      run: bundle exec jekyll build --config _config.yml,_config_prod.yml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
